[project]
name = "douban-app-client"
version = "0.1.0"
description = "A simple Python client for Douban, based on the android app interface."
authors = [{ name = "Dodge Pock", email = "dodgepock@gmail.com" }]
requires-python = ">=3.8"
dependencies = ["requests"]